[config]
timestep = 400.0
steps = 152345
export_step = 1000
export_directory = "export_files"
export_file_name_prefix = "SIM"
export_system_state = false # defaults to false
export_body_history = true # defaults to false
export_system_parameters_history = true # defaults to false
plot_system = true # defaults to false
plot_system_kinetic_energy = true # defaults to false
plot_system_potential_energy = false # defaults to false

[[system.bodies]]
name = "Sun"
mass = 1.989e30
[system.bodies.position]
x = 1.0
y = 2.0
[system.bodies.velocity]
x = 3.0
y = 4.0

[[system.bodies]]
name = "Earth"
mass = 5.972e24
[system.bodies.position]
x = 1.495978707e11
y = 0.0
[system.bodies.velocity]
x = 0.0
y = 4e5
